
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CARAT MINUS NUMBER ONE PLUS TWO VARIABLE ZEROempty :expr : term2 term1 term0term2 : PLUS NUMBER VARIABLE CARAT TWO\n            | MINUS NUMBER VARIABLE CARAT TWO\n            | NUMBER VARIABLE CARAT TWOterm1 : PLUS NUMBER VARIABLE CARAT ONE\n            | MINUS NUMBER VARIABLE CARAT ONE\n            | PLUS NUMBER VARIABLE\n            | MINUS NUMBER VARIABLE\n            | emptyterm0 : PLUS NUMBER VARIABLE CARAT ZERO\n            | MINUS NUMBER VARIABLE CARAT ZERO\n            | PLUS NUMBER\n            | MINUS NUMBER\n            | empty'
    
_lr_action_items = {'$end':([0,1,],[-1,0,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'empty':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> empty","S'",1,None,None,None),
  ('empty -> <empty>','empty',0,'p_empty','project.py',69),
  ('expr -> term2 term1 term0','expr',3,'p_expr','project.py',73),
  ('term2 -> PLUS NUMBER VARIABLE CARAT TWO','term2',5,'p_expr_term2','project.py',78),
  ('term2 -> MINUS NUMBER VARIABLE CARAT TWO','term2',5,'p_expr_term2','project.py',79),
  ('term2 -> NUMBER VARIABLE CARAT TWO','term2',4,'p_expr_term2','project.py',80),
  ('term1 -> PLUS NUMBER VARIABLE CARAT ONE','term1',5,'p_expr_term1','project.py',90),
  ('term1 -> MINUS NUMBER VARIABLE CARAT ONE','term1',5,'p_expr_term1','project.py',91),
  ('term1 -> PLUS NUMBER VARIABLE','term1',3,'p_expr_term1','project.py',92),
  ('term1 -> MINUS NUMBER VARIABLE','term1',3,'p_expr_term1','project.py',93),
  ('term1 -> empty','term1',1,'p_expr_term1','project.py',94),
  ('term0 -> PLUS NUMBER VARIABLE CARAT ZERO','term0',5,'p_expr_term0','project.py',104),
  ('term0 -> MINUS NUMBER VARIABLE CARAT ZERO','term0',5,'p_expr_term0','project.py',105),
  ('term0 -> PLUS NUMBER','term0',2,'p_expr_term0','project.py',106),
  ('term0 -> MINUS NUMBER','term0',2,'p_expr_term0','project.py',107),
  ('term0 -> empty','term0',1,'p_expr_term0','project.py',108),
]
